### ISSUE TITLE
query related to usage of airodump-ng

### ISSUE THREAD

**Issue by chetanbnaik** [futurice/whereareyou#4]
I see that you have are airodump-ng command on slave station to monitor the signal strength.

I have a question regarding that.
the airodump-ng [page](https://www.aircrack-ng.org/doku.php?id=airodump-ng) gives the following explanation of the PWR output:

> Signal level reported by the card. Its signification depends on the driver, but as the signal gets higher you get closer to the AP or the station. If the BSSID PWR is -1, then the driver doesn't support signal level reporting. If the PWR is -1 for a limited number of stations then this is for a packet which came from the AP to the client but the client transmissions are out of range for your card. Meaning you are hearing only 1/2 of the communication. If all clients have PWR as -1 then the driver doesn't support signal level reporting.

Does this mean, the PWR output displayed on slave station is the signal strength of the Access Point seen by the device? Or is it the signal strength of AP and device seen by slave station?

**Comment by WGierke** [comment]
Hi @chetanbnaik , thanks for your question and sorry for the delay.
I understand it as the signal strength of the AP seen by the device.
Best
Willi

**Comment by chetanbnaik** [comment]
Hi @WGierke 

As far as I have understood, it is between the slave station and the device. A passive wifi positioning is tricky unless there are OpenWRT compliant routers in use.
